wandb_version: 1

disable_env_checking:
  desc: null
  value: true
ignore_workers_failure:
  desc: null
  value: false
max_concurrent_trials:
  desc: null
  value: 1
framework:
  desc: null
  value: torch
num_workers:
  desc: null
  value: 0
env:
  desc: null
  value: CustomCarlaEnv
env_config:
  desc: null
  value:
    disable_env_checking: true
    ignore_workers_failure: false
model:
  desc: null
  value:
    fcnet_hiddens:
    - 1
    fcnet_activation: linear
lr:
  desc: null
  value: 0.0005
_wandb:
  desc: null
  value:
    python_version: 3.7.5
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702389902.455022
    t:
      1:
      - 30
      - 55
      2:
      - 30
      - 55
      3:
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.7.5
      5: 0.16.1
      8:
      - 8
      13: linux-x86_64
trial_log_path:
  desc: null
  value: /home/carla/PythonScripts/Stijn/DAI-AdaptiveCruiseControl/carla_RL/Checkpoints/PPO_2023-12-12_14-04-40/PPO_CustomCarlaEnv_6611f_00000_0_2023-12-12_14-04-43
